apiVersion: v1
kind: Pod
metadata:
  name: orders-sqs-client
  namespace: micro-tier
spec:
  serviceAccountName: orders
  containers:
  - name: aws-cli
    image: amazon/aws-cli
    command: ["/bin/sh"]
    args: ["-c", "sleep infinity"]
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"

    env:
      - name: AWS_REGION
        value: us-east-1

      # Fetch queue name from ConfigMap
      - name: SQS_QUEUE_NAME
        valueFrom:
          configMapKeyRef:
            name: orders
            key: RETAIL_ORDERS_MESSAGING_SQS_TOPIC
  restartPolicy: Never