apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orders
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Ahmedlekan/ecommerce_store.git
    targetRevision: main
    path: AWS/Kubernetes_manifest/aws_dataplane_k8manifest/04_orders

  destination:
    server: https://kubernetes.default.svc
    namespace: micro-tier

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
