# Maps the orders database and RabbitMQ credentials from AWS Secrets Manager
# into files that can be mounted by the orders app pod, PostgreSQL pod, and
# RabbitMQ pod.
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  namespace: micro-tier
  name: orders-runtime-secrets
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"
    objects: |
      - objectName: "orders-db-secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: "RETAIL_ORDERS_PERSISTENCE_USERNAME"
            objectAlias: "RETAIL_ORDERS_PERSISTENCE_USERNAME"
          - path: "RETAIL_ORDERS_PERSISTENCE_PASSWORD"
            objectAlias: "RETAIL_ORDERS_PERSISTENCE_PASSWORD"
      - objectName: "orders-rabbitmq-secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: "RETAIL_ORDERS_MESSAGING_RABBITMQ_USERNAME"
            objectAlias: "RETAIL_ORDERS_MESSAGING_RABBITMQ_USERNAME"
          - path: "RETAIL_ORDERS_MESSAGING_RABBITMQ_PASSWORD"
            objectAlias: "RETAIL_ORDERS_MESSAGING_RABBITMQ_PASSWORD"
